# Generated by Django 4.2.5 on 2023-09-25 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('single_rate', models.IntegerField()),
                ('single_dc', models.IntegerField()),
                ('double_rate', models.IntegerField()),
                ('double_dc', models.IntegerField()),
                ('box_rate', models.IntegerField()),
                ('box_dc', models.IntegerField()),
                ('super_rate', models.IntegerField()),
                ('super_dc', models.IntegerField()),
                ('first_rate', models.IntegerField()),
                ('second_rate', models.IntegerField()),
                ('third_rate', models.IntegerField()),
                ('fourth_rate', models.IntegerField()),
                ('fifth_rate', models.IntegerField()),
                ('guarantee_rate', models.IntegerField()),
                ('box_first_prize_rate', models.IntegerField()),
                ('box_series_rate', models.IntegerField()),
                ('_ratesingle1', models.IntegerField()),
                ('double2_rate', models.IntegerField()),
                ('first_dc', models.IntegerField()),
                ('second_dc', models.IntegerField()),
                ('third_dc', models.IntegerField()),
                ('fourth_dc', models.IntegerField()),
                ('fifth_dc', models.IntegerField()),
                ('guarantee_dc', models.IntegerField()),
                ('box_first_prize_dc', models.IntegerField()),
                ('box_series_dc', models.IntegerField()),
                ('single1_dc', models.IntegerField()),
                ('double2_dc', models.IntegerField()),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.agent')),
            ],
        ),
    ]
