# Generated by Django 4.2.5 on 2023-09-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playtime',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='playtime',
            name='start_time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
