# Generated by Django 4.2.5 on 2023-09-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_agentpackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentpackage',
            old_name='_ratesingle1',
            new_name='ratesingle1',
        ),
    ]
