# Generated by Django 4.2.5 on 2023-09-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename__ratesingle1_agentpackage_ratesingle1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentpackage',
            old_name='box_first_prize_rate',
            new_name='box_first_prize_prize',
        ),
        migrations.RenameField(
            model_name='agentpackage',
            old_name='box_series_rate',
            new_name='box_series_prize',
        ),
        migrations.RenameField(
            model_name='agentpackage',
            old_name='double2_rate',
            new_name='double2_prize',
        ),
        migrations.RenameField(
            model_name='agentpackage',
            old_name='fifth_rate',
            new_name='fifth_prize',
        ),
        migrations.RenameField(
            model_name='agentpackage',
            old_name='first_rate',
            new_name='first_prize',
        ),
        migrations.RenameField(
            model_name='agentpackage',
            old_name='fourth_rate',
            new_name='fourth_prize',
        ),
        migrations.RenameField(
            model_name='agentpackage',
            old_name='guarantee_rate',
            new_name='guarantee_prize',
        ),
        migrations.RenameField(
            model_name='agentpackage',
            old_name='ratesingle1',
            new_name='second_prize',
        ),
        migrations.RenameField(
            model_name='agentpackage',
            old_name='second_rate',
            new_name='single1_prize',
        ),
        migrations.RenameField(
            model_name='agentpackage',
            old_name='third_rate',
            new_name='third_prize',
        ),
    ]
