# Generated by Django 4.2.5 on 2023-09-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_box_first_prize_rate_agentpackage_box_first_prize_prize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentpackage',
            old_name='box_first_prize_prize',
            new_name='box_first_prize',
        ),
    ]
