# Generated by Django 4.2.5 on 2023-09-27 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('single_rate', models.FloatField()),
                ('single_dc', models.FloatField()),
                ('double_rate', models.FloatField()),
                ('double_dc', models.FloatField()),
                ('box_rate', models.FloatField()),
                ('box_dc', models.FloatField()),
                ('super_rate', models.FloatField()),
                ('super_dc', models.FloatField()),
                ('first_prize', models.FloatField()),
                ('first_dc', models.FloatField()),
                ('second_prize', models.FloatField()),
                ('second_dc', models.FloatField()),
                ('third_prize', models.FloatField()),
                ('third_dc', models.FloatField()),
                ('fourth_prize', models.FloatField()),
                ('fourth_dc', models.FloatField()),
                ('fifth_prize', models.FloatField()),
                ('fifth_dc', models.FloatField()),
                ('guarantee_prize', models.FloatField()),
                ('guarantee_dc', models.FloatField()),
                ('box_first_prize', models.FloatField()),
                ('box_first_prize_dc', models.FloatField()),
                ('box_series_prize', models.FloatField()),
                ('box_series_dc', models.FloatField()),
                ('single1_prize', models.FloatField()),
                ('single1_dc', models.FloatField()),
                ('double2_prize', models.FloatField()),
                ('double2_dc', models.FloatField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dealer')),
            ],
        ),
    ]
